server:
  port: 8700
spring:
  application:
    name: jvbo-springcloud-eureka-server-node1

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    root: info
    com.jvbo.springcloud.eureka: debug
    org.springframework: info