/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package site.jvbo.fun.okex.crawler.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OkexSpotTickerDataAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8742382153478392462L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OkexSpotTickerDataAvro\",\"namespace\":\"site.jvbo.fun.okex.crawler.avro\",\"fields\":[{\"name\":\"high\",\"type\":[\"string\",\"null\"]},{\"name\":\"vol\",\"type\":[\"string\",\"null\"]},{\"name\":\"last\",\"type\":[\"string\",\"null\"]},{\"name\":\"low\",\"type\":[\"string\",\"null\"]},{\"name\":\"buy\",\"type\":[\"string\",\"null\"]},{\"name\":\"change\",\"type\":[\"string\",\"null\"]},{\"name\":\"sell\",\"type\":[\"string\",\"null\"]},{\"name\":\"dayLow\",\"type\":[\"string\",\"null\"]},{\"name\":\"close\",\"type\":[\"string\",\"null\"]},{\"name\":\"dayHigh\",\"type\":[\"string\",\"null\"]},{\"name\":\"open\",\"type\":[\"string\",\"null\"]},{\"name\":\"timestamp\",\"type\":[\"long\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OkexSpotTickerDataAvro> ENCODER =
      new BinaryMessageEncoder<OkexSpotTickerDataAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OkexSpotTickerDataAvro> DECODER =
      new BinaryMessageDecoder<OkexSpotTickerDataAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OkexSpotTickerDataAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OkexSpotTickerDataAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OkexSpotTickerDataAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OkexSpotTickerDataAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OkexSpotTickerDataAvro from a ByteBuffer. */
  public static OkexSpotTickerDataAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence high;
  @Deprecated public java.lang.CharSequence vol;
  @Deprecated public java.lang.CharSequence last;
  @Deprecated public java.lang.CharSequence low;
  @Deprecated public java.lang.CharSequence buy;
  @Deprecated public java.lang.CharSequence change;
  @Deprecated public java.lang.CharSequence sell;
  @Deprecated public java.lang.CharSequence dayLow;
  @Deprecated public java.lang.CharSequence close;
  @Deprecated public java.lang.CharSequence dayHigh;
  @Deprecated public java.lang.CharSequence open;
  @Deprecated public java.lang.Long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OkexSpotTickerDataAvro() {}

  /**
   * All-args constructor.
   * @param high The new value for high
   * @param vol The new value for vol
   * @param last The new value for last
   * @param low The new value for low
   * @param buy The new value for buy
   * @param change The new value for change
   * @param sell The new value for sell
   * @param dayLow The new value for dayLow
   * @param close The new value for close
   * @param dayHigh The new value for dayHigh
   * @param open The new value for open
   * @param timestamp The new value for timestamp
   */
  public OkexSpotTickerDataAvro(java.lang.CharSequence high, java.lang.CharSequence vol, java.lang.CharSequence last, java.lang.CharSequence low, java.lang.CharSequence buy, java.lang.CharSequence change, java.lang.CharSequence sell, java.lang.CharSequence dayLow, java.lang.CharSequence close, java.lang.CharSequence dayHigh, java.lang.CharSequence open, java.lang.Long timestamp) {
    this.high = high;
    this.vol = vol;
    this.last = last;
    this.low = low;
    this.buy = buy;
    this.change = change;
    this.sell = sell;
    this.dayLow = dayLow;
    this.close = close;
    this.dayHigh = dayHigh;
    this.open = open;
    this.timestamp = timestamp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return high;
    case 1: return vol;
    case 2: return last;
    case 3: return low;
    case 4: return buy;
    case 5: return change;
    case 6: return sell;
    case 7: return dayLow;
    case 8: return close;
    case 9: return dayHigh;
    case 10: return open;
    case 11: return timestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: high = (java.lang.CharSequence)value$; break;
    case 1: vol = (java.lang.CharSequence)value$; break;
    case 2: last = (java.lang.CharSequence)value$; break;
    case 3: low = (java.lang.CharSequence)value$; break;
    case 4: buy = (java.lang.CharSequence)value$; break;
    case 5: change = (java.lang.CharSequence)value$; break;
    case 6: sell = (java.lang.CharSequence)value$; break;
    case 7: dayLow = (java.lang.CharSequence)value$; break;
    case 8: close = (java.lang.CharSequence)value$; break;
    case 9: dayHigh = (java.lang.CharSequence)value$; break;
    case 10: open = (java.lang.CharSequence)value$; break;
    case 11: timestamp = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'high' field.
   * @return The value of the 'high' field.
   */
  public java.lang.CharSequence getHigh() {
    return high;
  }

  /**
   * Sets the value of the 'high' field.
   * @param value the value to set.
   */
  public void setHigh(java.lang.CharSequence value) {
    this.high = value;
  }

  /**
   * Gets the value of the 'vol' field.
   * @return The value of the 'vol' field.
   */
  public java.lang.CharSequence getVol() {
    return vol;
  }

  /**
   * Sets the value of the 'vol' field.
   * @param value the value to set.
   */
  public void setVol(java.lang.CharSequence value) {
    this.vol = value;
  }

  /**
   * Gets the value of the 'last' field.
   * @return The value of the 'last' field.
   */
  public java.lang.CharSequence getLast() {
    return last;
  }

  /**
   * Sets the value of the 'last' field.
   * @param value the value to set.
   */
  public void setLast(java.lang.CharSequence value) {
    this.last = value;
  }

  /**
   * Gets the value of the 'low' field.
   * @return The value of the 'low' field.
   */
  public java.lang.CharSequence getLow() {
    return low;
  }

  /**
   * Sets the value of the 'low' field.
   * @param value the value to set.
   */
  public void setLow(java.lang.CharSequence value) {
    this.low = value;
  }

  /**
   * Gets the value of the 'buy' field.
   * @return The value of the 'buy' field.
   */
  public java.lang.CharSequence getBuy() {
    return buy;
  }

  /**
   * Sets the value of the 'buy' field.
   * @param value the value to set.
   */
  public void setBuy(java.lang.CharSequence value) {
    this.buy = value;
  }

  /**
   * Gets the value of the 'change' field.
   * @return The value of the 'change' field.
   */
  public java.lang.CharSequence getChange() {
    return change;
  }

  /**
   * Sets the value of the 'change' field.
   * @param value the value to set.
   */
  public void setChange(java.lang.CharSequence value) {
    this.change = value;
  }

  /**
   * Gets the value of the 'sell' field.
   * @return The value of the 'sell' field.
   */
  public java.lang.CharSequence getSell() {
    return sell;
  }

  /**
   * Sets the value of the 'sell' field.
   * @param value the value to set.
   */
  public void setSell(java.lang.CharSequence value) {
    this.sell = value;
  }

  /**
   * Gets the value of the 'dayLow' field.
   * @return The value of the 'dayLow' field.
   */
  public java.lang.CharSequence getDayLow() {
    return dayLow;
  }

  /**
   * Sets the value of the 'dayLow' field.
   * @param value the value to set.
   */
  public void setDayLow(java.lang.CharSequence value) {
    this.dayLow = value;
  }

  /**
   * Gets the value of the 'close' field.
   * @return The value of the 'close' field.
   */
  public java.lang.CharSequence getClose() {
    return close;
  }

  /**
   * Sets the value of the 'close' field.
   * @param value the value to set.
   */
  public void setClose(java.lang.CharSequence value) {
    this.close = value;
  }

  /**
   * Gets the value of the 'dayHigh' field.
   * @return The value of the 'dayHigh' field.
   */
  public java.lang.CharSequence getDayHigh() {
    return dayHigh;
  }

  /**
   * Sets the value of the 'dayHigh' field.
   * @param value the value to set.
   */
  public void setDayHigh(java.lang.CharSequence value) {
    this.dayHigh = value;
  }

  /**
   * Gets the value of the 'open' field.
   * @return The value of the 'open' field.
   */
  public java.lang.CharSequence getOpen() {
    return open;
  }

  /**
   * Sets the value of the 'open' field.
   * @param value the value to set.
   */
  public void setOpen(java.lang.CharSequence value) {
    this.open = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new OkexSpotTickerDataAvro RecordBuilder.
   * @return A new OkexSpotTickerDataAvro RecordBuilder
   */
  public static site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder newBuilder() {
    return new site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder();
  }

  /**
   * Creates a new OkexSpotTickerDataAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OkexSpotTickerDataAvro RecordBuilder
   */
  public static site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder newBuilder(site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder other) {
    return new site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder(other);
  }

  /**
   * Creates a new OkexSpotTickerDataAvro RecordBuilder by copying an existing OkexSpotTickerDataAvro instance.
   * @param other The existing instance to copy.
   * @return A new OkexSpotTickerDataAvro RecordBuilder
   */
  public static site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder newBuilder(site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro other) {
    return new site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder(other);
  }

  /**
   * RecordBuilder for OkexSpotTickerDataAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OkexSpotTickerDataAvro>
    implements org.apache.avro.data.RecordBuilder<OkexSpotTickerDataAvro> {

    private java.lang.CharSequence high;
    private java.lang.CharSequence vol;
    private java.lang.CharSequence last;
    private java.lang.CharSequence low;
    private java.lang.CharSequence buy;
    private java.lang.CharSequence change;
    private java.lang.CharSequence sell;
    private java.lang.CharSequence dayLow;
    private java.lang.CharSequence close;
    private java.lang.CharSequence dayHigh;
    private java.lang.CharSequence open;
    private java.lang.Long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.high)) {
        this.high = data().deepCopy(fields()[0].schema(), other.high);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.vol)) {
        this.vol = data().deepCopy(fields()[1].schema(), other.vol);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.last)) {
        this.last = data().deepCopy(fields()[2].schema(), other.last);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.low)) {
        this.low = data().deepCopy(fields()[3].schema(), other.low);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.buy)) {
        this.buy = data().deepCopy(fields()[4].schema(), other.buy);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.change)) {
        this.change = data().deepCopy(fields()[5].schema(), other.change);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.sell)) {
        this.sell = data().deepCopy(fields()[6].schema(), other.sell);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.dayLow)) {
        this.dayLow = data().deepCopy(fields()[7].schema(), other.dayLow);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.close)) {
        this.close = data().deepCopy(fields()[8].schema(), other.close);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.dayHigh)) {
        this.dayHigh = data().deepCopy(fields()[9].schema(), other.dayHigh);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.open)) {
        this.open = data().deepCopy(fields()[10].schema(), other.open);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[11].schema(), other.timestamp);
        fieldSetFlags()[11] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OkexSpotTickerDataAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.high)) {
        this.high = data().deepCopy(fields()[0].schema(), other.high);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.vol)) {
        this.vol = data().deepCopy(fields()[1].schema(), other.vol);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.last)) {
        this.last = data().deepCopy(fields()[2].schema(), other.last);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.low)) {
        this.low = data().deepCopy(fields()[3].schema(), other.low);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.buy)) {
        this.buy = data().deepCopy(fields()[4].schema(), other.buy);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.change)) {
        this.change = data().deepCopy(fields()[5].schema(), other.change);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.sell)) {
        this.sell = data().deepCopy(fields()[6].schema(), other.sell);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.dayLow)) {
        this.dayLow = data().deepCopy(fields()[7].schema(), other.dayLow);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.close)) {
        this.close = data().deepCopy(fields()[8].schema(), other.close);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.dayHigh)) {
        this.dayHigh = data().deepCopy(fields()[9].schema(), other.dayHigh);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.open)) {
        this.open = data().deepCopy(fields()[10].schema(), other.open);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[11].schema(), other.timestamp);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'high' field.
      * @return The value.
      */
    public java.lang.CharSequence getHigh() {
      return high;
    }

    /**
      * Sets the value of the 'high' field.
      * @param value The value of 'high'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setHigh(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.high = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'high' field has been set.
      * @return True if the 'high' field has been set, false otherwise.
      */
    public boolean hasHigh() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'high' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearHigh() {
      high = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'vol' field.
      * @return The value.
      */
    public java.lang.CharSequence getVol() {
      return vol;
    }

    /**
      * Sets the value of the 'vol' field.
      * @param value The value of 'vol'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setVol(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.vol = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'vol' field has been set.
      * @return True if the 'vol' field has been set, false otherwise.
      */
    public boolean hasVol() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'vol' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearVol() {
      vol = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'last' field.
      * @return The value.
      */
    public java.lang.CharSequence getLast() {
      return last;
    }

    /**
      * Sets the value of the 'last' field.
      * @param value The value of 'last'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setLast(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.last = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'last' field has been set.
      * @return True if the 'last' field has been set, false otherwise.
      */
    public boolean hasLast() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'last' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearLast() {
      last = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'low' field.
      * @return The value.
      */
    public java.lang.CharSequence getLow() {
      return low;
    }

    /**
      * Sets the value of the 'low' field.
      * @param value The value of 'low'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setLow(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.low = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'low' field has been set.
      * @return True if the 'low' field has been set, false otherwise.
      */
    public boolean hasLow() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'low' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearLow() {
      low = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'buy' field.
      * @return The value.
      */
    public java.lang.CharSequence getBuy() {
      return buy;
    }

    /**
      * Sets the value of the 'buy' field.
      * @param value The value of 'buy'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setBuy(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.buy = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'buy' field has been set.
      * @return True if the 'buy' field has been set, false otherwise.
      */
    public boolean hasBuy() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'buy' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearBuy() {
      buy = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'change' field.
      * @return The value.
      */
    public java.lang.CharSequence getChange() {
      return change;
    }

    /**
      * Sets the value of the 'change' field.
      * @param value The value of 'change'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setChange(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.change = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'change' field has been set.
      * @return True if the 'change' field has been set, false otherwise.
      */
    public boolean hasChange() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'change' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearChange() {
      change = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'sell' field.
      * @return The value.
      */
    public java.lang.CharSequence getSell() {
      return sell;
    }

    /**
      * Sets the value of the 'sell' field.
      * @param value The value of 'sell'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setSell(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.sell = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'sell' field has been set.
      * @return True if the 'sell' field has been set, false otherwise.
      */
    public boolean hasSell() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'sell' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearSell() {
      sell = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'dayLow' field.
      * @return The value.
      */
    public java.lang.CharSequence getDayLow() {
      return dayLow;
    }

    /**
      * Sets the value of the 'dayLow' field.
      * @param value The value of 'dayLow'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setDayLow(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.dayLow = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'dayLow' field has been set.
      * @return True if the 'dayLow' field has been set, false otherwise.
      */
    public boolean hasDayLow() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'dayLow' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearDayLow() {
      dayLow = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'close' field.
      * @return The value.
      */
    public java.lang.CharSequence getClose() {
      return close;
    }

    /**
      * Sets the value of the 'close' field.
      * @param value The value of 'close'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setClose(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.close = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'close' field has been set.
      * @return True if the 'close' field has been set, false otherwise.
      */
    public boolean hasClose() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'close' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearClose() {
      close = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'dayHigh' field.
      * @return The value.
      */
    public java.lang.CharSequence getDayHigh() {
      return dayHigh;
    }

    /**
      * Sets the value of the 'dayHigh' field.
      * @param value The value of 'dayHigh'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setDayHigh(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.dayHigh = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'dayHigh' field has been set.
      * @return True if the 'dayHigh' field has been set, false otherwise.
      */
    public boolean hasDayHigh() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'dayHigh' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearDayHigh() {
      dayHigh = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'open' field.
      * @return The value.
      */
    public java.lang.CharSequence getOpen() {
      return open;
    }

    /**
      * Sets the value of the 'open' field.
      * @param value The value of 'open'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setOpen(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.open = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'open' field has been set.
      * @return True if the 'open' field has been set, false otherwise.
      */
    public boolean hasOpen() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'open' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearOpen() {
      open = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder setTimestamp(java.lang.Long value) {
      validate(fields()[11], value);
      this.timestamp = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public site.jvbo.fun.okex.crawler.avro.OkexSpotTickerDataAvro.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OkexSpotTickerDataAvro build() {
      try {
        OkexSpotTickerDataAvro record = new OkexSpotTickerDataAvro();
        record.high = fieldSetFlags()[0] ? this.high : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.vol = fieldSetFlags()[1] ? this.vol : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.last = fieldSetFlags()[2] ? this.last : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.low = fieldSetFlags()[3] ? this.low : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.buy = fieldSetFlags()[4] ? this.buy : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.change = fieldSetFlags()[5] ? this.change : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.sell = fieldSetFlags()[6] ? this.sell : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.dayLow = fieldSetFlags()[7] ? this.dayLow : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.close = fieldSetFlags()[8] ? this.close : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.dayHigh = fieldSetFlags()[9] ? this.dayHigh : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.open = fieldSetFlags()[10] ? this.open : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.timestamp = fieldSetFlags()[11] ? this.timestamp : (java.lang.Long) defaultValue(fields()[11]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OkexSpotTickerDataAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<OkexSpotTickerDataAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OkexSpotTickerDataAvro>
    READER$ = (org.apache.avro.io.DatumReader<OkexSpotTickerDataAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
