server:
  port: 8090
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  rabbitmq:
    host: 192.168.137.235
    port: 5672
    username: jvbo
    password: 111111
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder.sql: trace
    org.hibernate.type.descriptor.sql.BasicExtractor.sql: trace
    com.jvbo: debug